# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 17:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=255)),
                ('startdate', models.DateField()),
                ('enddate', models.DateField()),
                ('plan', models.TextField()),
                ('others', models.ManyToManyField(related_name='travel_plan', to='travel.User')),
                ('planner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.User')),
            ],
        ),
    ]
